/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'social' : IDL.Null,
  'other' : IDL.Null,
  'personalDevelopment' : IDL.Null,
  'work' : IDL.Null,
  'study' : IDL.Null,
  'fitness' : IDL.Null,
  'health' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Date = IDL.Text;
export const TaskId = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'preferences' : IDL.Opt(IDL.Text),
});
export const CategorySummary = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'date' : Date,
  'completionPercentage' : IDL.Float64,
  'category' : IDL.Text,
});
export const TaskSuggestion = IDL.Record({
  'name' : IDL.Text,
  'category' : Category,
  'estimatedDuration' : IDL.Nat,
  'priority' : Priority,
  'reason' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'date' : Date,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'category' : Category,
  'estimatedDuration' : IDL.Nat,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, Category, Priority, IDL.Nat, Date, IDL.Int],
      [TaskId],
      [],
    ),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategorySummariesInRange' : IDL.Func(
      [Date, Date],
      [IDL.Vec(CategorySummary)],
      ['query'],
    ),
  'getCategorySummary' : IDL.Func(
      [Date],
      [IDL.Opt(CategorySummary)],
      ['query'],
    ),
  'getTaskSuggestions' : IDL.Func([], [IDL.Vec(TaskSuggestion)], ['query']),
  'getTasksForDate' : IDL.Func([Date], [IDL.Vec(Task)], ['query']),
  'getTasksForDateRange' : IDL.Func([Date, Date], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCategorySummary' : IDL.Func([CategorySummary], [], []),
  'toggleTaskCompletion' : IDL.Func([TaskId], [], []),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, Category, Priority, IDL.Nat, Date],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'other' : IDL.Null,
    'personalDevelopment' : IDL.Null,
    'work' : IDL.Null,
    'study' : IDL.Null,
    'fitness' : IDL.Null,
    'health' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Date = IDL.Text;
  const TaskId = IDL.Nat;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'preferences' : IDL.Opt(IDL.Text),
  });
  const CategorySummary = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'date' : Date,
    'completionPercentage' : IDL.Float64,
    'category' : IDL.Text,
  });
  const TaskSuggestion = IDL.Record({
    'name' : IDL.Text,
    'category' : Category,
    'estimatedDuration' : IDL.Nat,
    'priority' : Priority,
    'reason' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'date' : Date,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'category' : Category,
    'estimatedDuration' : IDL.Nat,
    'priority' : Priority,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, Category, Priority, IDL.Nat, Date, IDL.Int],
        [TaskId],
        [],
      ),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategorySummariesInRange' : IDL.Func(
        [Date, Date],
        [IDL.Vec(CategorySummary)],
        ['query'],
      ),
    'getCategorySummary' : IDL.Func(
        [Date],
        [IDL.Opt(CategorySummary)],
        ['query'],
      ),
    'getTaskSuggestions' : IDL.Func([], [IDL.Vec(TaskSuggestion)], ['query']),
    'getTasksForDate' : IDL.Func([Date], [IDL.Vec(Task)], ['query']),
    'getTasksForDateRange' : IDL.Func([Date, Date], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCategorySummary' : IDL.Func([CategorySummary], [], []),
    'toggleTaskCompletion' : IDL.Func([TaskId], [], []),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, Category, Priority, IDL.Nat, Date],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };