/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'social' : null } |
  { 'other' : null } |
  { 'personalDevelopment' : null } |
  { 'work' : null } |
  { 'study' : null } |
  { 'fitness' : null } |
  { 'health' : null };
export interface CategorySummary {
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'date' : string,
  'completionPercentage' : number,
  'category' : string,
}
export interface PremiumStatus {
  'identityCode' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'appliedAt' : bigint,
  'displayName' : [] | [string],
  'applied' : boolean,
  'premiumCode' : [] | [string],
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface PublicUserStats {
  'displayName' : string,
  'highestStreak' : bigint,
  'level' : bigint,
  'currentStreak' : bigint,
  'totalTaskCompletions' : bigint,
}
export interface Task {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'category' : Category,
  'estimatedDuration' : bigint,
  'priority' : Priority,
}
export interface TaskSuggestion {
  'name' : string,
  'category' : Category,
  'estimatedDuration' : bigint,
  'priority' : Priority,
  'reason' : string,
}
export interface UserProfile { 'name' : string, 'preferences' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'applyForPremium' : ActorMethod<[string], undefined>,
  'approvePremium' : ActorMethod<[Principal], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<
    [string, Category, Priority, bigint, string, bigint],
    bigint
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllPremiumApplications' : ActorMethod<
    [],
    Array<[Principal, PremiumStatus]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategorySummariesInRange' : ActorMethod<
    [string, string],
    Array<CategorySummary>
  >,
  'getCategorySummary' : ActorMethod<[string], [] | [CategorySummary]>,
  'getFriendList' : ActorMethod<[], Array<Principal>>,
  'getIncomingRequests' : ActorMethod<[], Array<Principal>>,
  'getMyIdentityCode' : ActorMethod<[], string>,
  'getMyPremiumApplication' : ActorMethod<[], [] | [PremiumStatus]>,
  'getOutgoingRequests' : ActorMethod<[], Array<Principal>>,
  'getPremiumApplicationsSummary' : ActorMethod<
    [],
    [bigint, Array<[Principal, PremiumStatus]>]
  >,
  'getPremiumStatus' : ActorMethod<[Principal], [] | [PremiumStatus]>,
  'getPublicStatsForUsers' : ActorMethod<
    [Array<Principal>],
    Array<[Principal, PublicUserStats]>
  >,
  'getTaskSuggestions' : ActorMethod<[], Array<TaskSuggestion>>,
  'getTasksForDate' : ActorMethod<[string], Array<Task>>,
  'getTasksForDateRange' : ActorMethod<[string, string], Array<Task>>,
  'getUniversalMasterCode' : ActorMethod<[], string>,
  'getUserIdentityCode' : ActorMethod<[Principal], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerPremium' : ActorMethod<[], boolean>,
  'isUserPremium' : ActorMethod<[Principal], boolean>,
  'redeemPremiumCode' : ActorMethod<[string], boolean>,
  'rejectPremium' : ActorMethod<[Principal], undefined>,
  'removeFriend' : ActorMethod<[Principal], undefined>,
  'requestPremiumStatus' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCategorySummary' : ActorMethod<[CategorySummary], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'updatePublicUserStats' : ActorMethod<[PublicUserStats], undefined>,
  'updateTask' : ActorMethod<
    [bigint, string, Category, Priority, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];