/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'social' : IDL.Null,
  'other' : IDL.Null,
  'personalDevelopment' : IDL.Null,
  'work' : IDL.Null,
  'study' : IDL.Null,
  'fitness' : IDL.Null,
  'health' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const PremiumStatus = IDL.Record({
  'identityCode' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'appliedAt' : IDL.Int,
  'monthlyExpiry' : IDL.Opt(IDL.Int),
  'displayName' : IDL.Opt(IDL.Text),
  'applied' : IDL.Bool,
  'premiumCode' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'preferences' : IDL.Opt(IDL.Text),
});
export const CategorySummary = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'date' : IDL.Text,
  'completionPercentage' : IDL.Float64,
  'category' : IDL.Text,
});
export const FriendPublicProfile = IDL.Record({
  'displayName' : IDL.Text,
  'earnedTitles' : IDL.Vec(IDL.Text),
  'highestStreak' : IDL.Nat,
  'activeTitle' : IDL.Opt(IDL.Text),
  'level' : IDL.Nat,
  'profilePictureUrl' : IDL.Opt(IDL.Text),
  'currentStreak' : IDL.Nat,
  'totalTaskCompletions' : IDL.Nat,
});
export const WheelData = IDL.Record({
  'totalSpinsUsed' : IDL.Nat,
  'earnedTitles' : IDL.Vec(IDL.Text),
  'totalSpinsEarned' : IDL.Nat,
});
export const PublicUserStats = IDL.Record({
  'displayName' : IDL.Text,
  'highestStreak' : IDL.Nat,
  'activeTitle' : IDL.Opt(IDL.Text),
  'level' : IDL.Nat,
  'currentStreak' : IDL.Nat,
  'totalTaskCompletions' : IDL.Nat,
});
export const TaskSuggestion = IDL.Record({
  'name' : IDL.Text,
  'category' : Category,
  'estimatedDuration' : IDL.Nat,
  'priority' : Priority,
  'reason' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'category' : Category,
  'estimatedDuration' : IDL.Nat,
  'priority' : Priority,
});
export const WheelType = IDL.Variant({
  'epic' : IDL.Null,
  'legendary' : IDL.Null,
  'common' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'applyForPremium' : IDL.Func([IDL.Text], [], []),
  'approvePremium' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func(
      [IDL.Text, Category, Priority, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getActiveTitle' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getAllMonthlySubscriptions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
      ['query'],
    ),
  'getAllPremiumApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PremiumStatus))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategorySummariesInRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CategorySummary)],
      ['query'],
    ),
  'getCategorySummary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CategorySummary)],
      ['query'],
    ),
  'getEarnedTitlesForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getEarnedTitlesForUsers' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getFriendList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFriendPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FriendPublicProfile)],
      ['query'],
    ),
  'getIncomingRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyIdentityCode' : IDL.Func([], [IDL.Text], ['query']),
  'getMyPremiumApplication' : IDL.Func([], [IDL.Opt(PremiumStatus)], ['query']),
  'getMyWheelData' : IDL.Func([], [WheelData], ['query']),
  'getOutgoingRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getPremiumApplicationsSummary' : IDL.Func(
      [],
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, PremiumStatus))],
      ['query'],
    ),
  'getPremiumStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PremiumStatus)],
      ['query'],
    ),
  'getProfilePicture' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getPublicStatsForUsers' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PublicUserStats))],
      ['query'],
    ),
  'getTaskSuggestions' : IDL.Func([], [IDL.Vec(TaskSuggestion)], []),
  'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksForDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getUniversalMasterCode' : IDL.Func([], [IDL.Text], ['query']),
  'getUserIdentityCode' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getUserMonthlyExpiry' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Int)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantMonthlyAccess' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerMonthlyActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerPremium' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserPremium' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'redeemPremiumCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'rejectPremium' : IDL.Func([IDL.Principal], [], []),
  'removeFriend' : IDL.Func([IDL.Principal], [], []),
  'requestPremiumStatus' : IDL.Func([], [], []),
  'revokeMonthlyAccess' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCategorySummary' : IDL.Func([CategorySummary], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'setActiveTitle' : IDL.Func([IDL.Text], [], []),
  'setProfilePicture' : IDL.Func([IDL.Text], [], []),
  'spinWheel' : IDL.Func([WheelType], [IDL.Text], []),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'updatePublicUserStats' : IDL.Func([PublicUserStats], [], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, Category, Priority, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'social' : IDL.Null,
    'other' : IDL.Null,
    'personalDevelopment' : IDL.Null,
    'work' : IDL.Null,
    'study' : IDL.Null,
    'fitness' : IDL.Null,
    'health' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const PremiumStatus = IDL.Record({
    'identityCode' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'appliedAt' : IDL.Int,
    'monthlyExpiry' : IDL.Opt(IDL.Int),
    'displayName' : IDL.Opt(IDL.Text),
    'applied' : IDL.Bool,
    'premiumCode' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'preferences' : IDL.Opt(IDL.Text),
  });
  const CategorySummary = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'date' : IDL.Text,
    'completionPercentage' : IDL.Float64,
    'category' : IDL.Text,
  });
  const FriendPublicProfile = IDL.Record({
    'displayName' : IDL.Text,
    'earnedTitles' : IDL.Vec(IDL.Text),
    'highestStreak' : IDL.Nat,
    'activeTitle' : IDL.Opt(IDL.Text),
    'level' : IDL.Nat,
    'profilePictureUrl' : IDL.Opt(IDL.Text),
    'currentStreak' : IDL.Nat,
    'totalTaskCompletions' : IDL.Nat,
  });
  const WheelData = IDL.Record({
    'totalSpinsUsed' : IDL.Nat,
    'earnedTitles' : IDL.Vec(IDL.Text),
    'totalSpinsEarned' : IDL.Nat,
  });
  const PublicUserStats = IDL.Record({
    'displayName' : IDL.Text,
    'highestStreak' : IDL.Nat,
    'activeTitle' : IDL.Opt(IDL.Text),
    'level' : IDL.Nat,
    'currentStreak' : IDL.Nat,
    'totalTaskCompletions' : IDL.Nat,
  });
  const TaskSuggestion = IDL.Record({
    'name' : IDL.Text,
    'category' : Category,
    'estimatedDuration' : IDL.Nat,
    'priority' : Priority,
    'reason' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'category' : Category,
    'estimatedDuration' : IDL.Nat,
    'priority' : Priority,
  });
  const WheelType = IDL.Variant({
    'epic' : IDL.Null,
    'legendary' : IDL.Null,
    'common' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'applyForPremium' : IDL.Func([IDL.Text], [], []),
    'approvePremium' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func(
        [IDL.Text, Category, Priority, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getActiveTitle' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getAllMonthlySubscriptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Int))],
        ['query'],
      ),
    'getAllPremiumApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PremiumStatus))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategorySummariesInRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CategorySummary)],
        ['query'],
      ),
    'getCategorySummary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CategorySummary)],
        ['query'],
      ),
    'getEarnedTitlesForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getEarnedTitlesForUsers' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getFriendList' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFriendPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FriendPublicProfile)],
        ['query'],
      ),
    'getIncomingRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyIdentityCode' : IDL.Func([], [IDL.Text], ['query']),
    'getMyPremiumApplication' : IDL.Func(
        [],
        [IDL.Opt(PremiumStatus)],
        ['query'],
      ),
    'getMyWheelData' : IDL.Func([], [WheelData], ['query']),
    'getOutgoingRequests' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getPremiumApplicationsSummary' : IDL.Func(
        [],
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, PremiumStatus))],
        ['query'],
      ),
    'getPremiumStatus' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PremiumStatus)],
        ['query'],
      ),
    'getProfilePicture' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getPublicStatsForUsers' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PublicUserStats))],
        ['query'],
      ),
    'getTaskSuggestions' : IDL.Func([], [IDL.Vec(TaskSuggestion)], []),
    'getTasksForDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksForDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getUniversalMasterCode' : IDL.Func([], [IDL.Text], ['query']),
    'getUserIdentityCode' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getUserMonthlyExpiry' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Int)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantMonthlyAccess' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerMonthlyActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerPremium' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserPremium' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'redeemPremiumCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'rejectPremium' : IDL.Func([IDL.Principal], [], []),
    'removeFriend' : IDL.Func([IDL.Principal], [], []),
    'requestPremiumStatus' : IDL.Func([], [], []),
    'revokeMonthlyAccess' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCategorySummary' : IDL.Func([CategorySummary], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'setActiveTitle' : IDL.Func([IDL.Text], [], []),
    'setProfilePicture' : IDL.Func([IDL.Text], [], []),
    'spinWheel' : IDL.Func([WheelType], [IDL.Text], []),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'updatePublicUserStats' : IDL.Func([PublicUserStats], [], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, Category, Priority, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };