/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CategorySummary {
    totalTasks: bigint;
    completedTasks: bigint;
    date: string;
    completionPercentage: number;
    category: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: bigint;
    date: string;
    name: string;
    createdAt: bigint;
    completed: boolean;
    category: Category;
    estimatedDuration: bigint;
    priority: Priority;
}
export interface FriendPublicProfile {
    displayName: string;
    earnedTitles: Array<string>;
    highestStreak: bigint;
    activeTitle?: string;
    level: bigint;
    profilePictureUrl?: string;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TaskSuggestion {
    name: string;
    category: Category;
    estimatedDuration: bigint;
    priority: Priority;
    reason: string;
}
export interface PremiumStatus {
    identityCode: string;
    status: Variant_pending_approved_rejected;
    appliedAt: bigint;
    monthlyExpiry?: bigint;
    displayName?: string;
    applied: boolean;
    premiumCode?: string;
}
export interface WheelData {
    totalSpinsUsed: bigint;
    earnedTitles: Array<string>;
    totalSpinsEarned: bigint;
}
export interface PublicUserStats {
    displayName: string;
    highestStreak: bigint;
    activeTitle?: string;
    level: bigint;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
}
export interface UserProfile {
    name: string;
    preferences?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    social = "social",
    other = "other",
    personalDevelopment = "personalDevelopment",
    work = "work",
    study = "study",
    fitness = "fitness",
    health = "health"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum WheelType {
    epic = "epic",
    legendary = "legendary",
    common = "common"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptFriendRequest(userId: Principal): Promise<void>;
    applyForPremium(displayName: string): Promise<void>;
    approvePremium(applicant: Principal): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTask(name: string, category: Category, priority: Priority, estimatedDuration: bigint, date: string, createdAt: bigint): Promise<bigint>;
    deleteTask(taskId: bigint): Promise<void>;
    getActiveTitle(user: Principal): Promise<string | null>;
    getAllMonthlySubscriptions(): Promise<Array<[Principal, bigint]>>;
    getAllPremiumApplications(): Promise<Array<[Principal, PremiumStatus]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategorySummariesInRange(startDate: string, endDate: string): Promise<Array<CategorySummary>>;
    getCategorySummary(date: string): Promise<CategorySummary | null>;
    getEarnedTitlesForUser(user: Principal): Promise<Array<string>>;
    getEarnedTitlesForUsers(users: Array<Principal>): Promise<Array<[Principal, Array<string>]>>;
    getFriendList(): Promise<Array<Principal>>;
    getFriendPublicProfile(friend: Principal): Promise<FriendPublicProfile | null>;
    getIncomingRequests(): Promise<Array<Principal>>;
    getMyIdentityCode(): Promise<string>;
    getMyPremiumApplication(): Promise<PremiumStatus | null>;
    getMyWheelData(): Promise<WheelData>;
    getOutgoingRequests(): Promise<Array<Principal>>;
    getPremiumApplicationsSummary(): Promise<[bigint, Array<[Principal, PremiumStatus]>]>;
    getPremiumStatus(user: Principal): Promise<PremiumStatus | null>;
    getProfilePicture(user: Principal): Promise<string | null>;
    getPublicStatsForUsers(users: Array<Principal>): Promise<Array<[Principal, PublicUserStats]>>;
    getTaskSuggestions(): Promise<Array<TaskSuggestion>>;
    getTasksForDate(date: string): Promise<Array<Task>>;
    getTasksForDateRange(startDate: string, endDate: string): Promise<Array<Task>>;
    getUniversalMasterCode(): Promise<string>;
    getUserIdentityCode(user: Principal): Promise<string>;
    getUserMonthlyExpiry(user: Principal): Promise<bigint | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantMonthlyAccess(user: Principal, months: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerMonthlyActive(): Promise<boolean>;
    isCallerPremium(): Promise<boolean>;
    isUserPremium(user: Principal): Promise<boolean>;
    redeemPremiumCode(code: string): Promise<boolean>;
    rejectPremium(applicant: Principal): Promise<void>;
    removeFriend(friendId: Principal): Promise<void>;
    requestPremiumStatus(): Promise<void>;
    revokeMonthlyAccess(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCategorySummary(summary: CategorySummary): Promise<void>;
    sendFriendRequest(userId: Principal): Promise<void>;
    setActiveTitle(title: string): Promise<void>;
    setProfilePicture(url: string): Promise<void>;
    spinWheel(wheelType: WheelType): Promise<string>;
    toggleTaskCompletion(taskId: bigint): Promise<void>;
    updatePublicUserStats(stats: PublicUserStats): Promise<void>;
    updateTask(taskId: bigint, name: string, category: Category, priority: Priority, estimatedDuration: bigint, date: string): Promise<void>;
}
import type { Category as _Category, CategorySummary as _CategorySummary, FriendPublicProfile as _FriendPublicProfile, PremiumStatus as _PremiumStatus, Priority as _Priority, PublicUserStats as _PublicUserStats, Task as _Task, TaskSuggestion as _TaskSuggestion, UserProfile as _UserProfile, UserRole as _UserRole, WheelType as _WheelType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async applyForPremium(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForPremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForPremium(arg0);
            return result;
        }
    }
    async approvePremium(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePremium(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: string, arg1: Category, arg2: Priority, arg3: bigint, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg1), to_candid_Priority_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg1), to_candid_Priority_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getActiveTitle(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTitle(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTitle(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMonthlySubscriptions(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlySubscriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlySubscriptions();
            return result;
        }
    }
    async getAllPremiumApplications(): Promise<Array<[Principal, PremiumStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPremiumApplications();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPremiumApplications();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategorySummariesInRange(arg0: string, arg1: string): Promise<Array<CategorySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategorySummariesInRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategorySummariesInRange(arg0, arg1);
            return result;
        }
    }
    async getCategorySummary(arg0: string): Promise<CategorySummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategorySummary(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategorySummary(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEarnedTitlesForUser(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarnedTitlesForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarnedTitlesForUser(arg0);
            return result;
        }
    }
    async getEarnedTitlesForUsers(arg0: Array<Principal>): Promise<Array<[Principal, Array<string>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEarnedTitlesForUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEarnedTitlesForUsers(arg0);
            return result;
        }
    }
    async getFriendList(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendList();
            return result;
        }
    }
    async getFriendPublicProfile(arg0: Principal): Promise<FriendPublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendPublicProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendPublicProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomingRequests(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingRequests();
            return result;
        }
    }
    async getMyIdentityCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyIdentityCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyIdentityCode();
            return result;
        }
    }
    async getMyPremiumApplication(): Promise<PremiumStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPremiumApplication();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPremiumApplication();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWheelData(): Promise<WheelData> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWheelData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWheelData();
            return result;
        }
    }
    async getOutgoingRequests(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutgoingRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutgoingRequests();
            return result;
        }
    }
    async getPremiumApplicationsSummary(): Promise<[bigint, Array<[Principal, PremiumStatus]>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getPremiumApplicationsSummary();
                return [
                    result[0],
                    from_candid_vec_n15(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPremiumApplicationsSummary();
            return [
                result[0],
                from_candid_vec_n15(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getPremiumStatus(arg0: Principal): Promise<PremiumStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPremiumStatus(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPremiumStatus(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfilePicture(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilePicture(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilePicture(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicStatsForUsers(arg0: Array<Principal>): Promise<Array<[Principal, PublicUserStats]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicStatsForUsers(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicStatsForUsers(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskSuggestions(): Promise<Array<TaskSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskSuggestions();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskSuggestions();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForDate(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForDate(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForDate(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForDateRange(arg0: string, arg1: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForDateRange(arg0, arg1);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForDateRange(arg0, arg1);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUniversalMasterCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUniversalMasterCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUniversalMasterCode();
            return result;
        }
    }
    async getUserIdentityCode(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserIdentityCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserIdentityCode(arg0);
            return result;
        }
    }
    async getUserMonthlyExpiry(arg0: Principal): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMonthlyExpiry(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMonthlyExpiry(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantMonthlyAccess(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantMonthlyAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantMonthlyAccess(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerMonthlyActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerMonthlyActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerMonthlyActive();
            return result;
        }
    }
    async isCallerPremium(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerPremium();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerPremium();
            return result;
        }
    }
    async isUserPremium(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserPremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserPremium(arg0);
            return result;
        }
    }
    async redeemPremiumCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemPremiumCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemPremiumCode(arg0);
            return result;
        }
    }
    async rejectPremium(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPremium(arg0);
            return result;
        }
    }
    async removeFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async requestPremiumStatus(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPremiumStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPremiumStatus();
            return result;
        }
    }
    async revokeMonthlyAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeMonthlyAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeMonthlyAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCategorySummary(arg0: CategorySummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCategorySummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCategorySummary(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async setActiveTitle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveTitle(arg0);
            return result;
        }
    }
    async setProfilePicture(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfilePicture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfilePicture(arg0);
            return result;
        }
    }
    async spinWheel(arg0: WheelType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.spinWheel(to_candid_WheelType_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spinWheel(to_candid_WheelType_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleTaskCompletion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return result;
        }
    }
    async updatePublicUserStats(arg0: PublicUserStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublicUserStats(to_candid_PublicUserStats_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublicUserStats(to_candid_PublicUserStats_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: Category, arg3: Priority, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg2), to_candid_Priority_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_Category_n10(this._uploadFile, this._downloadFile, arg2), to_candid_Priority_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_Category_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_FriendPublicProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendPublicProfile): FriendPublicProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PremiumStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PremiumStatus): PremiumStatus {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PublicUserStats_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserStats): PublicUserStats {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_TaskSuggestion_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskSuggestion): TaskSuggestion {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategorySummary]): CategorySummary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FriendPublicProfile]): FriendPublicProfile | null {
    return value.length === 0 ? null : from_candid_FriendPublicProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PremiumStatus]): PremiumStatus | null {
    return value.length === 0 ? null : from_candid_PremiumStatus_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    identityCode: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    appliedAt: bigint;
    monthlyExpiry: [] | [bigint];
    displayName: [] | [string];
    applied: boolean;
    premiumCode: [] | [string];
}): {
    identityCode: string;
    status: Variant_pending_approved_rejected;
    appliedAt: bigint;
    monthlyExpiry?: bigint;
    displayName?: string;
    applied: boolean;
    premiumCode?: string;
} {
    return {
        identityCode: value.identityCode,
        status: from_candid_variant_n19(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        monthlyExpiry: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.monthlyExpiry)),
        displayName: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.displayName)),
        applied: value.applied,
        premiumCode: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.premiumCode))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferences: [] | [string];
}): {
    name: string;
    preferences?: string;
} {
    return {
        name: value.name,
        preferences: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.preferences))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    earnedTitles: Array<string>;
    highestStreak: bigint;
    activeTitle: [] | [string];
    level: bigint;
    profilePictureUrl: [] | [string];
    currentStreak: bigint;
    totalTaskCompletions: bigint;
}): {
    displayName: string;
    earnedTitles: Array<string>;
    highestStreak: bigint;
    activeTitle?: string;
    level: bigint;
    profilePictureUrl?: string;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
} {
    return {
        displayName: value.displayName,
        earnedTitles: value.earnedTitles,
        highestStreak: value.highestStreak,
        activeTitle: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.activeTitle)),
        level: value.level,
        profilePictureUrl: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.profilePictureUrl)),
        currentStreak: value.currentStreak,
        totalTaskCompletions: value.totalTaskCompletions
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    highestStreak: bigint;
    activeTitle: [] | [string];
    level: bigint;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
}): {
    displayName: string;
    highestStreak: bigint;
    activeTitle?: string;
    level: bigint;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
} {
    return {
        displayName: value.displayName,
        highestStreak: value.highestStreak,
        activeTitle: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.activeTitle)),
        level: value.level,
        currentStreak: value.currentStreak,
        totalTaskCompletions: value.totalTaskCompletions
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    category: _Category;
    estimatedDuration: bigint;
    priority: _Priority;
    reason: string;
}): {
    name: string;
    category: Category;
    estimatedDuration: bigint;
    priority: Priority;
    reason: string;
} {
    return {
        name: value.name,
        category: from_candid_Category_n38(_uploadFile, _downloadFile, value.category),
        estimatedDuration: value.estimatedDuration,
        priority: from_candid_Priority_n40(_uploadFile, _downloadFile, value.priority),
        reason: value.reason
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    name: string;
    createdAt: bigint;
    completed: boolean;
    category: _Category;
    estimatedDuration: bigint;
    priority: _Priority;
}): {
    id: bigint;
    date: string;
    name: string;
    createdAt: bigint;
    completed: boolean;
    category: Category;
    estimatedDuration: bigint;
    priority: Priority;
} {
    return {
        id: value.id,
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        completed: value.completed,
        category: from_candid_Category_n38(_uploadFile, _downloadFile, value.category),
        estimatedDuration: value.estimatedDuration,
        priority: from_candid_Priority_n40(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _PremiumStatus]): [Principal, PremiumStatus] {
    return [
        value[0],
        from_candid_PremiumStatus_n17(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _PublicUserStats]): [Principal, PublicUserStats] {
    return [
        value[0],
        from_candid_PublicUserStats_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    other: null;
} | {
    personalDevelopment: null;
} | {
    work: null;
} | {
    study: null;
} | {
    fitness: null;
} | {
    health: null;
}): Category {
    return "social" in value ? Category.social : "other" in value ? Category.other : "personalDevelopment" in value ? Category.personalDevelopment : "work" in value ? Category.work : "study" in value ? Category.study : "fitness" in value ? Category.fitness : "health" in value ? Category.health : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _PremiumStatus]>): Array<[Principal, PremiumStatus]> {
    return value.map((x)=>from_candid_tuple_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _PublicUserStats]>): Array<[Principal, PublicUserStats]> {
    return value.map((x)=>from_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskSuggestion>): Array<TaskSuggestion> {
    return value.map((x)=>from_candid_TaskSuggestion_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n43(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PublicUserStats_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicUserStats): _PublicUserStats {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WheelType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WheelType): _WheelType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferences?: string;
}): {
    name: string;
    preferences: [] | [string];
} {
    return {
        name: value.name,
        preferences: value.preferences ? candid_some(value.preferences) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    highestStreak: bigint;
    activeTitle?: string;
    level: bigint;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
}): {
    displayName: string;
    highestStreak: bigint;
    activeTitle: [] | [string];
    level: bigint;
    currentStreak: bigint;
    totalTaskCompletions: bigint;
} {
    return {
        displayName: value.displayName,
        highestStreak: value.highestStreak,
        activeTitle: value.activeTitle ? candid_some(value.activeTitle) : candid_none(),
        level: value.level,
        currentStreak: value.currentStreak,
        totalTaskCompletions: value.totalTaskCompletions
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    social: null;
} | {
    other: null;
} | {
    personalDevelopment: null;
} | {
    work: null;
} | {
    study: null;
} | {
    fitness: null;
} | {
    health: null;
} {
    return value == Category.social ? {
        social: null
    } : value == Category.other ? {
        other: null
    } : value == Category.personalDevelopment ? {
        personalDevelopment: null
    } : value == Category.work ? {
        work: null
    } : value == Category.study ? {
        study: null
    } : value == Category.fitness ? {
        fitness: null
    } : value == Category.health ? {
        health: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WheelType): {
    epic: null;
} | {
    legendary: null;
} | {
    common: null;
} {
    return value == WheelType.epic ? {
        epic: null
    } : value == WheelType.legendary ? {
        legendary: null
    } : value == WheelType.common ? {
        common: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
